### ISSUE TITLE
Add token authentication

### ISSUE THREAD

**Issue by william-herring** [william-herring/bor#2]
This should be done using the authtoken provided by Django Rest Framework. It will also require a login page and we will have to update some of the get requests made from the client to provide the token. The login screen will replace JoinTeamScreen as home route.

**Comment by maen08** [comment]
Will help out with this task. Got to know your project from Tim's discord. Cheers!

**Comment by william-herring** [comment]
Thanks Stanley, I appreciate it. I actually started on it a few commits back but ended up removing it because I didn't want to deal with authentication before I had sorted the team join out, so feel free to check that out if you want.

**Comment by william-herring** [comment]
Will begin on this later today, I have assigned myself to this task.

**Comment by william-herring** [comment]
Authentication added in API, tomorrow I will set up everything with the client login/registration, etc. Did a few tests, all seems to be working as expected.
https://github.com/william-herring/bor/commit/9629d73bb85df43eefb64f0077308e1564cb2128

**Comment by william-herring** [comment]
Finished, see commit https://github.com/william-herring/bor/commit/4f0160d0c29842303b1a0b3b057d60ffd6509da8
